-- Add image_url to recipes so each recipe row can reference a stored food photo.
-- URLs point to objects in the private `images` storage bucket and are served
-- to clients only via short-lived signed URLs generated by the server.

ALTER TABLE public.recipes
  ADD COLUMN IF NOT EXISTS image_url TEXT;
